remote_theme: samarsault/plainwhite-jekyll

title: "My Portfolio"
author: Chanhyuk David Lee
description: "This is my personal portfolio website"
email: chan3684@kaist.ac.kr

url: "https://david3684.github.io"
baseurl: ""

github_username: david3684

social:
  github: "https://github.com/david3684"

