#!/usr/bin/env python3
"""Fetch citation counts from Semantic Scholar and write to _data/citations.yml."""

import json
import os
import sys
import urllib.request
import urllib.error
from datetime import datetime, timezone

PAPERS = [
    "2412.12153",
    "2509.07530",
    "2503.22178",
    "2602.16813",
    "2605.10518",
    "2606.24773",
    "2607.00714",
]

def fetch_citations(arxiv_ids):
    ids = ["arXiv:" + id for id in arxiv_ids]
    body = json.dumps({"ids": ids}).encode()
    url = "https://api.semanticscholar.org/graph/v1/paper/batch?fields=citationCount"
    req = urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            return json.loads(resp.read())
    except urllib.error.HTTPError as e:
        print(f"HTTP error {e.code}: {e.reason}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)

def main():
    results = fetch_citations(PAPERS)
    updated = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = [f"# Auto-generated by scripts/fetch_citations.py — do not edit manually"]
    lines.append(f"updated: \"{updated}\"")
    lines.append("citations:")
    for i, arxiv_id in enumerate(PAPERS):
        item = results[i] if i < len(results) else None
        count = item.get("citationCount", 0) if item else 0
        lines.append(f"  \"{arxiv_id}\": {count}")

    out_path = os.path.join(os.path.dirname(__file__), "..", "_data", "citations.yml")
    with open(out_path, "w") as f:
        f.write("\n".join(lines) + "\n")

    for i, arxiv_id in enumerate(PAPERS):
        count = results[i].get("citationCount", "?") if i < len(results) else "?"
        print(f"  {arxiv_id}: {count}")
    print(f"Written to _data/citations.yml")

if __name__ == "__main__":
    main()
